version: '3.7'

services:
  web:
    image: ubu-apa1
    ports:
      - "8080:80"
    depends_on:
      - "db"
    restart: always
    volumes:
      - /var/lib/docker/volumes/http-boarding/_data:/var/www/html/
  db:
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rent
      - MYSQL_USER=rent
      - MYSQL_PASSWORD=rent
      - MYSQL_DATABASE=rent
    volumes:
      - /var/lib/docker/volumes/dbg/_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - "db"
    ports:
      - 8081:80
    environment:
      -  PMA_ARBITRARY=1
